### ISSUE TITLE
(if true 'Yep') issue

### ISSUE THREAD

**Issue by emaphp** [lisphp/lisphp#16]
I forked this project yesterday. I still dont know if this is supposed to be ok as I never worked with lisp before. The issue appeared when running these examples:

(if true "Yep")
(if true 'Yep')

The first example work as expected, by returning 'Yep' (or so i suppose). The second one shows an error. I tried to figure it out by myself and I think I found the reason. Looks like the problem is related to the regex used to parse a string literal. The solution came after replacing

const STRING_PATTERN = '/^"([^"\\]|\\.)_"|\'([^\'\\]|\\.)_\'/';

with

const STRING_PATTERN = '/^"([^"\\]|\\.)_"|^\'([^\'\\]|\\.)_\'/'; 

in the Parser class (notice the additional ^ symbol right after the second pipe).

**Comment by igorw** [comment]
@emaphp thanks so much for this ticket. I've pushed a fix. can you confirm?

**Comment by emaphp** [comment]
it's working.
