### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by igorw** [lisphp/lisphp#2]
It should be possible to comment out lines using semicolons:

```
; add two numbers
(+ 1 2)
```

**Comment by JonathanAquino** [comment]
Comments would be great. They currently sort of work but sort of don't.

;;; This comment is fine.

(if true
    ;; This comment messes things up.
    'a'
    'b')

**Comment by JonathanAquino** [comment]
I added comment support in this pull request: https://github.com/lisphp/lisphp/pull/17

**Comment by igorw** [comment]
Fixed by #17.
